create table user_metadata (
	id BIGSERIAL NOT NULL,
	github_id VARCHAR(50) NOT NULL PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	avatar_url VARCHAR(250) NOT NULL,
	bio TEXT,
	phone_number VARCHAR(50),
	email_marketing_consent VARCHAR(50) NOT NULL,
	text_message_consent VARCHAR(50) NOT NULL,
	teacher VARCHAR(50) NOT NULL,
	stripe_client_id VARCHAR(40),
	crypto_wallet_address VARCHAR(40)
);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (1, '97-170-3242', 'jpenticoot0', 'https://robohash.org/cumqueomnisea.png?size=50x50&set=set1', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', '312-216-2979', false, true, false, 'cd421c2d-54a0-4630-99c9-0b95b897e700', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (2, '69-494-5080', 'hkennaway1', 'https://robohash.org/voluptatibusperferendistempora.png?size=50x50&set=set1', null, null, false, true, true, 'e10d88a4-24a0-4121-bb59-c973a621252c', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (3, '34-521-5329', 'cblandamere2', 'https://robohash.org/quaeratdoloribussit.png?size=50x50&set=set1', null, '371-492-0237', false, false, false, '4644eaba-a593-4354-9cc4-fb55788b797d', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (4, '04-744-2680', 'ctreves3', 'https://robohash.org/atreiciendisvoluptatem.png?size=50x50&set=set1', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', null, false, false, true, 'e278a2fd-8bbc-48ac-999c-07074d90979f', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (5, '22-757-9266', 'fibbitt4', 'https://robohash.org/eiusrerumarchitecto.png?size=50x50&set=set1', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', null, true, false, false, '47ca3406-e971-406c-b4b1-6d7d32140da0', '0ae61dc9-ae90-42f2-8a71-810fb800a3e0');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (6, '37-846-6804', 'pmclaughlan5', 'https://robohash.org/cumsolutaab.png?size=50x50&set=set1', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', '475-339-4155', true, false, true, '709cc66d-cfb7-482d-ae4f-5b89f14a6fc8', '9efae363-0c11-4ce0-8795-827836236c67');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (7, '89-149-5561', 'lgregine6', 'https://robohash.org/laboriosammagnamet.png?size=50x50&set=set1', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', null, false, false, false, 'a8cface6-957e-4652-89d4-7db26ec56931', '1c3b3615-3887-481d-8d6b-a0fa4795cba6');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (8, '67-940-6688', 'jcockshut7', 'https://robohash.org/repudiandaeconsequaturnostrum.png?size=50x50&set=set1', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, false, true, false, 'd5afb113-1d55-49db-90c2-3d843251c6fc', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (9, '30-275-0891', 'ldecarteret8', 'https://robohash.org/velevenietrepudiandae.png?size=50x50&set=set1', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', '655-871-1423', true, false, false, 'd095b621-25c0-4463-9419-8bbec5f6415f', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (10, '71-521-6305', 'langelo9', 'https://robohash.org/quasarchitectofugiat.png?size=50x50&set=set1', 'Integer ac neque. Duis bibendum.', null, false, false, false, '19bba23c-bbea-4f32-9fce-bb2f5e26b4e9', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (11, '42-620-5000', 'mboheya', 'https://robohash.org/iustodignissimosminima.png?size=50x50&set=set1', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', null, true, true, false, 'f3b083b1-4ff2-4093-8fa4-80b007a83ace', '28cb6622-76a5-4a5e-98b2-d6753ab88db6');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (12, '73-470-6659', 'hcostinb', 'https://robohash.org/easolutalaborum.png?size=50x50&set=set1', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', null, true, false, false, 'e665ff3e-eed2-4c80-9d0e-3421f4d9347e', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (13, '10-359-9695', 'churlesc', 'https://robohash.org/voluptatumcumnon.png?size=50x50&set=set1', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '321-363-7631', false, true, false, '0e3a2339-cfb9-4097-997d-f200059ed6d0', 'e483b97c-574a-4ee1-b074-8eba34c70986');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (14, '52-256-3492', 'bstranged', 'https://robohash.org/asperioresetest.png?size=50x50&set=set1', null, '830-482-6545', false, true, false, 'b928726b-7d63-4c49-8e3a-8033bd9b3f01', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (15, '44-303-0286', 'bpentycoste', 'https://robohash.org/quiaperferendissapiente.png?size=50x50&set=set1', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '667-933-4383', false, true, false, 'f3450786-3b63-49f8-b386-8cb57bbde00e', 'e7532b8c-3604-4807-915c-0eabdd05f60a');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (16, '29-615-3795', 'cwhitingf', 'https://robohash.org/totamsitvoluptatem.png?size=50x50&set=set1', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', '169-138-1995', true, false, false, 'b2f4d217-638c-4d5b-9070-cbf638eccf5a', 'fecba9b9-afc4-4307-afdd-71885b4a48b9');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (17, '66-093-9126', 'mskitralg', 'https://robohash.org/saepeasperiorespossimus.png?size=50x50&set=set1', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.', '352-339-8700', false, true, true, 'b4956764-a6ea-4ff4-ae9f-617822ad0c3a', '20012d97-a95b-4fa8-8bca-0b43e9c2adb5');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (18, '66-383-5701', 'asimonianh', 'https://robohash.org/omnisvoluptatibusillo.png?size=50x50&set=set1', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '492-217-9870', true, true, false, 'f0f2726b-d3d9-422d-8df7-0fec4781dbd6', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (19, '45-535-1636', 'ztoopini', 'https://robohash.org/inundeaccusantium.png?size=50x50&set=set1', null, null, true, false, false, 'c1669d9b-ea4c-4a30-91d2-8ccac0a05c6a', '51d8e3dc-fed0-424f-933c-ee18bf24e8f3');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (20, '27-059-8631', 'nodooganj', 'https://robohash.org/excepturiminimaat.png?size=50x50&set=set1', null, null, true, true, false, 'b63447e2-a1cb-4bf0-a1b5-daa543c031ce', 'be3bd1a5-8285-4ab2-84f0-b1ec5ec3df3f');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (21, '18-324-3718', 'alanktreek', 'https://robohash.org/quaeratdoloresnesciunt.png?size=50x50&set=set1', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', '653-153-4642', true, false, false, '35661d78-4ff5-4939-9a27-5d3aef927866', 'c915cf8e-673c-47c0-a20e-0333927591de');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (22, '83-862-5652', 'kbayntonl', 'https://robohash.org/commodisapientedoloribus.png?size=50x50&set=set1', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', '116-644-4739', true, false, true, '16e931e3-9893-40c2-a540-2220695f50e9', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (23, '51-051-1071', 'smauldenm', 'https://robohash.org/autautcumque.png?size=50x50&set=set1', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '571-899-4687', true, true, true, 'f876ff46-827d-4936-8bf8-f55768235ffa', 'bc5d873d-a75f-4fa0-a5de-d7a3c42faee7');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (24, '42-432-5727', 'kkinneallyn', 'https://robohash.org/accusantiumeanobis.png?size=50x50&set=set1', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '528-635-8921', true, false, true, '593167fa-31e7-4764-bee9-6f5ded8cacaf', '14afe184-2198-4189-8aa2-1abbb57c0906');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (25, '62-886-2422', 'sedmotto', 'https://robohash.org/possimusnamnumquam.png?size=50x50&set=set1', 'Morbi a ipsum. Integer a nibh.', '151-744-0690', false, false, true, '3f8c6926-a7ba-473a-beec-f004a2a34202', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (26, '16-626-8681', 'mbrotherhedp', 'https://robohash.org/consequaturdignissimosdoloribus.png?size=50x50&set=set1', null, null, false, false, false, 'c3e4edb2-09da-4406-baaf-c69f611b2011', '9a3cdfee-1306-42ff-8ea4-2e13a8f597b5');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (27, '20-037-6898', 'csjollemaq', 'https://robohash.org/sitisteeos.png?size=50x50&set=set1', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '669-964-3135', false, true, false, 'dd36e046-5329-4424-9f78-ebac93c5f0ad', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (28, '90-450-7383', 'ktiffanyr', 'https://robohash.org/fugitetnon.png?size=50x50&set=set1', null, null, false, false, false, '51edf5c2-c09e-4083-802d-8b88139e988a', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (29, '58-806-7312', 'bwithams', 'https://robohash.org/sintatquererum.png?size=50x50&set=set1', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '569-288-4336', false, true, false, '1eeee15c-657d-4ac6-87c3-fc9358e3d140', '840a8404-14f2-428a-9b04-3d6c292f614a');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (30, '50-174-0935', 'vcuzent', 'https://robohash.org/etadipiscinon.png?size=50x50&set=set1', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.', null, false, true, true, '6c90e696-50be-45fb-bb9e-126cd34624e3', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (31, '07-020-9086', 'kfranceschiu', 'https://robohash.org/enimquiimpedit.png?size=50x50&set=set1', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '880-876-5274', false, true, true, 'c2535567-2194-455a-afa4-f95ac4930ad6', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (32, '75-544-9673', 'wpingv', 'https://robohash.org/quienimsit.png?size=50x50&set=set1', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', null, false, false, true, 'b674eafd-d520-4015-af8a-746e75d23f4e', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (33, '21-748-8464', 'besbergerw', 'https://robohash.org/distinctioquosuscipit.png?size=50x50&set=set1', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '851-485-7588', true, true, false, '329c4608-0b3a-429b-a66e-04b8ac886f1d', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (34, '75-364-3293', 'sroparsx', 'https://robohash.org/ducimusetenim.png?size=50x50&set=set1', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '284-837-5059', false, true, false, 'a62a3f32-ae93-46dd-82e1-348e3531fb88', 'b73bbf70-4acb-45bd-a7a9-bbd383c1b197');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (35, '86-748-1627', 'aglowaczy', 'https://robohash.org/nihilfugiataut.png?size=50x50&set=set1', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', null, false, true, false, '14bca704-74f5-4bf8-aa31-79a6198383b2', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (36, '37-099-4037', 'zaleavyz', 'https://robohash.org/voluptatumlaudantiumneque.png?size=50x50&set=set1', 'Donec posuere metus vitae ipsum.', '627-210-5854', false, true, true, '1242071d-3a2e-414a-915a-5ca66ef73b22', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (37, '48-053-3621', 'msalasar10', 'https://robohash.org/omnisrationetempora.png?size=50x50&set=set1', null, '381-231-5903', false, false, true, '0ff6d76a-486c-458f-bfc9-5e11a7becf1d', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (38, '89-557-7215', 'lhutchence11', 'https://robohash.org/quisuteaque.png?size=50x50&set=set1', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '829-570-0977', false, true, false, 'ed27ebf4-3e05-4fbb-8183-ee07253a1c8e', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (39, '68-456-2563', 'drosendahl12', 'https://robohash.org/ametutvoluptatem.png?size=50x50&set=set1', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '774-695-0392', false, true, false, '60241e89-e948-41e3-b77f-8285f1850d7d', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (40, '73-332-2237', 'rpeoples13', 'https://robohash.org/eaquevelitquia.png?size=50x50&set=set1', null, '130-361-0522', false, false, false, 'aa45ea15-4720-4287-9ffb-be815ce8febc', '091dd658-be75-4799-90ab-fe0ec0383e47');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (41, '00-483-7914', 'rbauldrey14', 'https://robohash.org/euminciduntmagni.png?size=50x50&set=set1', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', null, false, false, false, '7f2aedc1-6716-4db3-8beb-ffa9c16dca20', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (42, '13-976-1295', 'ehalmkin15', 'https://robohash.org/eosblanditiisquia.png?size=50x50&set=set1', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', '528-501-1877', false, false, true, 'a6ca5935-b5df-4f20-b96e-c07d629fe288', '48a61819-be7e-480e-90ac-467779f3b193');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (43, '11-048-8923', 'jthoresbie16', 'https://robohash.org/etodioqui.png?size=50x50&set=set1', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '704-253-3137', true, false, false, '7cb68f71-27b4-421f-9bba-114b49707c78', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (44, '48-421-8491', 'clehrian17', 'https://robohash.org/maioresvoluptaset.png?size=50x50&set=set1', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', null, false, true, false, '2779768b-b2c8-441e-8111-31e887fae0cb', 'f0512555-25fd-47dd-9781-5b5cbe831cb2');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (45, '88-435-9662', 'aleopard18', 'https://robohash.org/indistinctiosoluta.png?size=50x50&set=set1', null, '570-645-5522', true, false, false, 'e48abeb6-0993-4f55-ab61-e7bb2e3c1cb0', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (46, '10-507-6203', 'gkyberd19', 'https://robohash.org/nobisidfacere.png?size=50x50&set=set1', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '186-953-0517', true, true, true, '806216db-d65e-4956-a35b-1d6cd2297bce', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (47, '53-196-4521', 'alopes1a', 'https://robohash.org/doloremnullablanditiis.png?size=50x50&set=set1', null, null, false, false, false, '8d248747-1150-40b7-91da-4c777b3bcdc2', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (48, '94-456-9880', 'asamples1b', 'https://robohash.org/perferendisreprehenderitaut.png?size=50x50&set=set1', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', null, true, false, false, '31cd3776-a963-4c28-9daa-3dbaa2fde491', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (49, '17-228-6141', 'ltreat1c', 'https://robohash.org/iurefacilisid.png?size=50x50&set=set1', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', null, false, false, false, 'a76e3edc-296b-4c47-9ae3-5c39bdf6fab1', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (50, '18-978-4681', 'ntreherne1d', 'https://robohash.org/eiusmagninisi.png?size=50x50&set=set1', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '854-364-1255', false, true, true, 'f9711752-c688-44b0-a589-e4f198c0b806', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (51, '39-615-9654', 'cpridmore1e', 'https://robohash.org/adipisciautemqui.png?size=50x50&set=set1', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '160-671-8174', true, true, true, '450cd580-3298-42df-9a41-148a4b5d40b8', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (52, '32-930-8757', 'tbacke1f', 'https://robohash.org/voluptatemquaesed.png?size=50x50&set=set1', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', '780-581-0898', false, true, false, 'a6ceafaa-1233-4d2d-a3a1-754f42138795', 'e89d18e7-a424-441b-818f-7e3f91a83e9e');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (53, '31-839-4744', 'lalexsandrev1g', 'https://robohash.org/magnamvelitmolestias.png?size=50x50&set=set1', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', null, true, true, false, 'db8836e1-b6be-4112-a134-36f547629e71', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (54, '10-421-3166', 'rdoole1h', 'https://robohash.org/recusandaealiastotam.png?size=50x50&set=set1', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', null, true, true, false, 'af53100e-cb0c-4643-a115-c8fee24e894f', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (55, '57-217-8178', 'gguirard1i', 'https://robohash.org/temporeeumnihil.png?size=50x50&set=set1', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', null, true, true, true, '0b692e9f-07df-450a-9456-b31ffa6767f1', '8dd38245-a80e-40dc-997c-925addf38dbf');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (56, '83-000-4012', 'tsuttling1j', 'https://robohash.org/uterrordelectus.png?size=50x50&set=set1', null, null, true, false, false, '12c8f866-4bdf-469b-9e91-23d7bf1b5029', 'bf960b98-9dcd-4045-ace4-20b07706f1ab');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (57, '98-381-7825', 'mmulvey1k', 'https://robohash.org/voluptatumautenim.png?size=50x50&set=set1', null, '280-156-1994', false, true, true, '6ce3ed28-044b-4c7e-859b-ccd65a5501a7', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (58, '22-349-4701', 'thehnke1l', 'https://robohash.org/aautfugit.png?size=50x50&set=set1', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '337-137-1001', true, true, true, '71315521-541b-4c1a-b54f-45332f086a7d', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (59, '60-977-9218', 'kfitzsymons1m', 'https://robohash.org/inventoreestenim.png?size=50x50&set=set1', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '926-173-9856', true, true, false, 'a3e33358-d313-4713-a1fe-dade17b5feb8', '961f7ee4-a903-40a8-957d-91c5025aeb42');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (60, '01-986-8282', 'cbrelsford1n', 'https://robohash.org/laborequisquia.png?size=50x50&set=set1', null, null, false, false, true, 'a9013b77-5a10-4489-8a64-f1cc30c13e44', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (61, '59-290-5057', 'jsherrington1o', 'https://robohash.org/cumverorerum.png?size=50x50&set=set1', 'Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '703-220-4591', false, false, true, '5ba92628-eb87-4b5b-80f6-a9b198931b3a', '565a9a74-91c6-43b5-acc6-d0f06cc3333c');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (62, '74-050-7649', 'adewi1p', 'https://robohash.org/providentnisiconsectetur.png?size=50x50&set=set1', null, null, true, true, true, 'e5f33494-085e-4757-b71f-7c3e938c9d61', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (63, '63-485-3255', 'rrowsell1q', 'https://robohash.org/quamconsequunturmollitia.png?size=50x50&set=set1', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', null, false, true, false, 'c6fe86ad-21a3-4790-9a06-146e51a84306', 'f0720934-95f1-4b1e-9090-317e3890e832');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (64, '25-680-3963', 'hgurry1r', 'https://robohash.org/remetnihil.png?size=50x50&set=set1', null, null, true, false, false, '55cdbe9a-da6c-41df-87d0-77e4f000200d', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (65, '04-930-6613', 'nhammer1s', 'https://robohash.org/noneumoptio.png?size=50x50&set=set1', 'Pellentesque at nulla.', null, false, true, true, 'f7259448-2fa8-40e2-8139-57a0d3172c96', '21a10256-60ce-4ed3-8e34-b576c6f0d535');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (66, '04-170-4116', 'sboarer1t', 'https://robohash.org/adautquas.png?size=50x50&set=set1', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '490-946-0550', true, true, false, '9578d956-d942-487a-a6c7-3df6bb26a089', 'c54b821f-eced-42e0-aa3a-1cac81bb01d9');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (67, '07-308-8653', 'wvivyan1u', 'https://robohash.org/errorabvoluptas.png?size=50x50&set=set1', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', '918-720-7033', false, false, true, 'eb00bf70-df18-433c-b255-85a02d6a6c94', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (68, '56-285-5583', 'fhevner1v', 'https://robohash.org/etrerumreiciendis.png?size=50x50&set=set1', null, '777-281-6493', false, false, false, '5a13ba76-a895-4c6d-9b86-896740a09826', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (69, '28-479-6080', 'pshelvey1w', 'https://robohash.org/maximeconsequaturaut.png?size=50x50&set=set1', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '507-623-9656', true, false, true, 'b7b583d3-11af-4bf4-b735-c00709e9e767', 'c15e646b-54e6-434d-b3bc-28d8a0afc319');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (70, '07-402-8670', 'zunthank1x', 'https://robohash.org/estreprehenderitillo.png?size=50x50&set=set1', 'Etiam vel augue.', '992-164-8594', true, false, true, 'e78ca8d5-3053-4fa5-ba16-07d5284675eb', '8d4c5a6a-033a-430a-9c27-f22094684b26');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (71, '33-216-4252', 'cbortol1y', 'https://robohash.org/modideseruntpariatur.png?size=50x50&set=set1', null, '202-621-0819', true, false, false, 'a84d7563-4e9a-498e-a693-e85977d2ce92', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (72, '00-429-4012', 'kjarrelt1z', 'https://robohash.org/nemoeaperferendis.png?size=50x50&set=set1', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', null, false, true, false, 'b448c683-1c22-40d0-b671-22c1f7698f86', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (73, '24-675-1527', 'mluipold20', 'https://robohash.org/inciduntsitquam.png?size=50x50&set=set1', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '895-726-4933', false, true, false, '1f2ecbb9-9e13-4ee6-a766-9c9a492bbc61', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (74, '87-014-8813', 'rgreenly21', 'https://robohash.org/commodinesciuntconsectetur.png?size=50x50&set=set1', 'In quis justo. Maecenas rhoncus aliquam lacus.', '167-257-7377', false, false, false, '29c28ac6-fe03-48b6-afbe-54a60a4dfac9', '39c4f10f-3c32-46c5-8cea-be3f0e034cbf');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (75, '29-154-6014', 'jlovatt22', 'https://robohash.org/doloresauttempore.png?size=50x50&set=set1', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', '143-986-1419', true, false, true, '81cf0a51-564a-4681-8cdc-4b984faa6c79', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (76, '06-250-5197', 'elloyd23', 'https://robohash.org/excepturiporroquis.png?size=50x50&set=set1', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '874-150-7899', false, true, true, '57602401-16cc-4fff-a605-4b7bfd4b1fb9', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (77, '91-861-0198', 'meveling24', 'https://robohash.org/enimaperiambeatae.png?size=50x50&set=set1', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', '863-383-2819', true, true, true, '6068e476-d2b8-47da-8571-39c506f7784b', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (78, '19-229-2028', 'kaviss25', 'https://robohash.org/aspernaturvelitnihil.png?size=50x50&set=set1', null, '295-630-7168', false, false, false, 'f144c5d9-a7c4-46b8-b8b9-cfe78e3c0b6f', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (79, '57-182-6561', 'bheims26', 'https://robohash.org/easuntillum.png?size=50x50&set=set1', null, '864-847-7370', true, false, false, 'c2f7a77e-fc4d-42c4-853b-d45848526969', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (80, '48-808-3987', 'jdangerfield27', 'https://robohash.org/inipsamaperiam.png?size=50x50&set=set1', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', '691-760-3729', true, true, true, '86ca3ef7-8939-4526-8a0b-ef57fc3f1389', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (81, '83-764-1214', 'tgorham28', 'https://robohash.org/totamnemoincidunt.png?size=50x50&set=set1', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', '820-928-8003', false, true, false, 'bd56f48a-59c0-4f4b-8c6c-28a45934dd43', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (82, '82-578-3700', 'trickman29', 'https://robohash.org/perferendiscorruptivoluptatem.png?size=50x50&set=set1', null, '548-590-2026', false, true, true, '3149fa90-0e79-454c-8c52-b0cfb0115bdf', '60e9ddc3-9b66-4532-8c63-d67ae313a42f');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (83, '42-830-0642', 'cport2a', 'https://robohash.org/molestiasestqui.png?size=50x50&set=set1', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', '611-587-0491', false, false, true, '7c6f0b11-a6f1-4796-ab77-96b2ec3a9ae2', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (84, '77-108-1280', 'vniesegen2b', 'https://robohash.org/quiitaquesint.png?size=50x50&set=set1', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', null, false, false, false, '9ff0ff21-7a3e-4409-9acd-966080be7822', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (85, '75-330-1250', 'iaberkirdo2c', 'https://robohash.org/autquoaut.png?size=50x50&set=set1', null, '823-719-4110', false, true, true, '03c5f341-20e0-4124-bb75-2cb283355c90', '5b1832bd-4892-4b5a-ae1f-2b1f60a0bfc4');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (86, '77-093-7833', 'fbullman2d', 'https://robohash.org/architectorerumquia.png?size=50x50&set=set1', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '383-130-8290', true, false, true, '958ddc25-f9d3-4c59-8c05-cea8c490877e', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (87, '14-813-4031', 'mconnichie2e', 'https://robohash.org/autemetet.png?size=50x50&set=set1', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', '251-651-9296', true, true, true, 'b00d47c4-9650-495e-a65c-b59bad2699a9', 'd64d73fb-0b2e-41dc-aed7-0ab3c727a881');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (88, '85-095-0510', 'ddebanke2f', 'https://robohash.org/utvoluptatemdolor.png?size=50x50&set=set1', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '457-760-0457', false, false, true, 'cd881a80-b3d8-472c-81cd-8cb6797d47d6', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (89, '88-024-0941', 'skillerby2g', 'https://robohash.org/rationeducimusdolorem.png?size=50x50&set=set1', null, null, false, true, true, '031d3d6f-99bf-49b6-9b71-097b91f074d6', '074ac020-6cbf-49e5-ad88-51cfffa658ca');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (90, '20-406-2279', 'doliffe2h', 'https://robohash.org/undenostrumdistinctio.png?size=50x50&set=set1', null, null, true, false, false, '90436329-924d-4e0a-b82c-6ac158f9f66e', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (91, '47-913-5563', 'rocarney2i', 'https://robohash.org/sitquodvoluptates.png?size=50x50&set=set1', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', '819-452-3071', false, true, true, 'f0c59860-33fd-42e4-a1cc-1883aaac7e28', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (92, '24-202-3383', 'lpennicard2j', 'https://robohash.org/magnamnihilautem.png?size=50x50&set=set1', 'Vivamus vestibulum sagittis sapien.', null, false, true, false, '38b36aea-9e50-45e4-af3c-6cf841dabccc', '89c24a31-295c-41e7-8eb6-d8f468821a21');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (93, '03-370-6216', 'zkerby2k', 'https://robohash.org/perferendissintautem.png?size=50x50&set=set1', null, null, true, false, true, 'cb8704b6-704b-495e-adff-681ced871c51', 'b5179cd5-e125-40c2-b518-e851977b3f22');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (94, '53-393-5112', 'ljansson2l', 'https://robohash.org/eiusmolestiasconsectetur.png?size=50x50&set=set1', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '776-538-3330', false, true, false, '8de6d7fa-b0ff-409c-92be-285c6bd1446f', 'f00bf8fd-9a21-4aae-85a7-8cd3fb12f7f0');
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (95, '26-224-3072', 'scurme2m', 'https://robohash.org/harumsedplaceat.png?size=50x50&set=set1', null, null, true, false, true, 'c1bd149c-bb50-4991-a196-538496e94617', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (96, '74-163-8638', 'oroizin2n', 'https://robohash.org/cumqueiustomodi.png?size=50x50&set=set1', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', null, false, true, false, '46ad65b0-3a1f-4890-923a-ee85438a9a5d', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (97, '45-429-7087', 'sblazic2o', 'https://robohash.org/quisquiet.png?size=50x50&set=set1', null, null, false, true, true, '76c78cd2-428a-4d4a-99b6-482cbd8cc740', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (98, '14-957-7942', 'gcookley2p', 'https://robohash.org/minimaestenim.png?size=50x50&set=set1', null, '169-441-8576', false, true, false, '3c33ab23-9023-425d-aff9-5a13ac078d3c', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (99, '25-809-1827', 'rstenner2q', 'https://robohash.org/architectoestmodi.png?size=50x50&set=set1', null, '648-749-2191', true, false, true, '7ae869e5-68bb-49d0-9697-c4a5525e5d1e', null);
insert into user_metadata (id, github_id, username, avatar_url, bio, phone_number, email_marketing_consent, text_message_consent, teacher, stripe_client_id, crypto_wallet_address) values (100, '59-099-5060', 'ahammelberg2r', 'https://robohash.org/laudantiumquiillum.png?size=50x50&set=set1', 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', '152-768-3285', true, true, false, '0b34d92f-4f90-431d-9274-389f22d52591', null);
